[package]
name = "rolling-median"
description = "Compute the median using a 'rolling' (online) algorithm"
license = "0BSD"
repository = "https://github.com/lordmulder/rolling-median"
version = "1.5.4"
edition = "2018"

[dev-dependencies]
rand_pcg = { version = "0.9.0", default-features = false }
